### ISSUE TITLE
Compile error - openSUSE 12.3 ( undefined reference to `av_guess_format' and ‘V4L2_CID_PRIVATE_BASE’ undeclared)

### ISSUE THREAD

**Issue by tosiara** [sackmotion/motion#11]
Hello,

I'm using sources from GIT: git clone https://github.com/sackmotion/motion.git

When I try to compile on openSUSE 12.3 I get error:

gcc -g -O2 -D_REENTRANT -DHAVE_FFMPEG -I/usr/local/include/ffmpeg -DMOTION_V4L2 -DMOTION_V4L2_OLD -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=i686 -Wall -DVERSION=\"Git-8619d7c17ce112e7196975905c6e840f345141ba\" -Dsysconfdir=\"/usr/local/etc\"    -c -o track.o track.c
track.c: In function ‘servo_center’:
track.c:566:18: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
track.c: In function ‘uvc_center’:
track.c:936:29: error: storage size of ‘control_s’ isn’t known
track.c:938:24: error: ‘V4L2_CID_PRIVATE_BASE’ undeclared (first use in this function)
track.c:938:24: note: each undeclared identifier is reported only once for each function it appears in
track.c:941:24: error: ‘VIDIOC_S_CTRL’ undeclared (first use in this function)
track.c:951:31: error: storage size of ‘queryctrl’ isn’t known
track.c:954:24: error: ‘VIDIOC_QUERYCTRL’ undeclared (first use in this function)
track.c:951:31: warning: unused variable ‘queryctrl’ [-Wunused-variable]
track.c:936:29: warning: unused variable ‘control_s’ [-Wunused-variable]
track.c:984:25: error: storage size of ‘control_s’ isn’t known
track.c:984:25: warning: unused variable ‘control_s’ [-Wunused-variable]
track.c: In function ‘uvc_move’:
track.c:1080:29: error: storage size of ‘control_s’ isn’t known
track.c:1082:24: error: ‘V4L2_CID_PRIVATE_BASE’ undeclared (first use in this function)
track.c:1085:24: error: ‘VIDIOC_S_CTRL’ undeclared (first use in this function)
track.c:1080:29: warning: unused variable ‘control_s’ [-Wunused-variable]
track.c:1136:25: error: storage size of ‘control_s’ isn’t known
track.c:1136:25: warning: unused variable ‘control_s’ [-Wunused-variable]
make: **\* [track.o] Error 1

On the net I found a workaround - to modify track.h and add there a line:
# include linux/videodev2.h

This allows motion to compile, but on the link stage I get another error:

Motion object files compiled.

Linking Motion...

---

gcc -L/usr/local/lib -o motion motion.o logger.o conf.o draw.o jpegutils.o vloopback_motion.o video.o video2.o video_common.o netcam.o netcam_ftp.o netcam_jpeg.o netcam_wget.o track.o alg.o event.o picture.o rotate.o webhttpd.o stream.o md5.o ffmpeg.o  -lm  -lpthread -ljpeg -L/usr/local/lib -lavformat -lavcodec -lavutil -lm -lz 
ffmpeg.o: In function `get_oformat':
/home/test/motion/ffmpeg.c:391: undefined reference to`av_guess_format'
/home/test/motion/ffmpeg.c:349: undefined reference to `av_guess_format'
/home/test/motion/ffmpeg.c:366: undefined reference to`av_guess_format'
/home/test/motion/ffmpeg.c:399: undefined reference to `av_guess_format'
/home/test/motion/ffmpeg.c:373: undefined reference to`av_guess_format'
ffmpeg.o:/home/test/motion/ffmpeg.c:384: more undefined references to `av_guess_format' follow
collect2: error: ld returned 1 exit status
make: **\* [motion] Error 1

My system: Linux hostname 3.7.10-1.1-desktop #1 SMP PREEMPT Thu Feb 28 15:06:29 UTC 2013 (82d3f21) i686 athlon i386 GNU/Linux

openSUSE 12.3 32bit

"certified" ffmpeg compiled from source: http://sourceforge.net/projects/motion/files/Related%20Projects/ffmpeg-for-motion-3.2.5/ffmpeg-cvs-20060306-certified-with-motion-3.2.5.tar.gz/download

What else I'm missing? How to solve this issue?

Thanks

**Comment by tosiara** [comment]
Upgraded ffmpeg to 0.11.3, got another error:

## Linking Motion...

gcc -L/usr/local/lib -o motion motion.o logger.o conf.o draw.o jpegutils.o vloopback_motion.o video.o video2.o video_common.o netcam.o netcam_ftp.o netcam_jpeg.o netcam_wget.o track.o alg.o event.o picture.o rotate.o webhttpd.o stream.o md5.o ffmpeg.o  -lm  -lpthread -ljpeg -L/usr/local/lib -lavformat -lavcodec -lavutil -lm -lz -L/usr/lib64 -lmysqlclient -lz
ffmpeg.o: In function `mpeg1_write_trailer':
/root/motion-master/ffmpeg.c:267: undefined reference to`put_buffer'
/root/motion-master/ffmpeg.c:268: undefined reference to `put_flush_packet'
ffmpeg.o: In function`ffmpeg_init':
/root/motion-master/ffmpeg.c:299: undefined reference to `file_protocol'
/root/motion-master/ffmpeg.c:300: undefined reference to`file_protocol'
/root/motion-master/ffmpeg.c:301: undefined reference to `file_protocol'
/root/motion-master/ffmpeg.c:302: undefined reference to`file_protocol'
ffmpeg.o: In function `ffmpeg_open':
/root/motion-master/ffmpeg.c:573: undefined reference to`av_set_parameters'
/root/motion-master/ffmpeg.c:678: undefined reference to `url_fopen'
/root/motion-master/ffmpeg.c:720: undefined reference to`av_write_header'
/root/motion-master/ffmpeg.c:692: undefined reference to `url_fopen'
ffmpeg.o: In function`ffmpeg_close':
/root/motion-master/ffmpeg.c:794: undefined reference to `url_fclose'
collect2: error: ld returned 1 exit status
make: **\* [motion] Error 1

**Comment by tosiara** [comment]
Ok, using ffmpeg 0.11.3 and added -DFF_API_NEW_AVIO to Makefile's CFLAGS - motion linked successfully. Tested gspca webcam - works. Tested Easycap device - segfault :(

**Comment by tosiara** [comment]
Compilation issue can be resolved by config params --with-ffmpeg and --with-ffmpeg-headers pointing to correct libavcodec.so and avformat.h locations (ex, ffmpeg compiled from sources)
