### ISSUE TITLE
Can not build with ffmpeg 0.11

### ISSUE THREAD

**Issue by p5n** [sackmotion/motion#3]
```
ffmpeg.c:26:10: warning: #warning ************************************************** [-Wcpp]
ffmpeg.c:27:10: warning: #warning Your version of FFmpeg is newer than version 0.4.8 [-Wcpp]
ffmpeg.c:28:10: warning: #warning Newer versions of ffmpeg do not support MPEG1 with [-Wcpp]
ffmpeg.c:29:10: warning: #warning non-standard framerate. MPEG1 will be disabled for [-Wcpp]
ffmpeg.c:30:10: warning: #warning normal video output. You can still use mpeg4 and [-Wcpp]
ffmpeg.c:31:10: warning: #warning and mpeg4ms which are both better in terms of size [-Wcpp]
ffmpeg.c:32:10: warning: #warning and quality. MPEG1 is always used for timelapse. [-Wcpp]
ffmpeg.c:33:10: warning: #warning Please read the Motion Guide for more information. [-Wcpp]
ffmpeg.c:34:10: warning: #warning Note that this is not an error message! [-Wcpp]
ffmpeg.c:35:10: warning: #warning ************************************************** [-Wcpp]
ffmpeg.c:76:29: error: unknown type name 'URLContext'
ffmpeg.c:112:1: error: unknown type name 'URLProtocol'
ffmpeg.c:113:5: error: field name not in record or union initializer
ffmpeg.c:113:5: error: (near initialization for 'mpeg1_file_protocol')
ffmpeg.c:113:5: warning: initialization makes integer from pointer without a cast [enabled by default]
ffmpeg.c:113:5: warning: (near initialization for 'mpeg1_file_protocol') [enabled by default]
ffmpeg.c:114:5: error: field name not in record or union initializer
ffmpeg.c:114:5: error: (near initialization for 'mpeg1_file_protocol')
ffmpeg.c:114:17: error: 'file_open_append' undeclared here (not in a function)
ffmpeg.c:115:1: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:115:1: warning: (near initialization for 'mpeg1_file_protocol') [enabled by default]
ffmpeg.c:131:22: error: unknown type name 'URLContext'
ffmpeg.c:155:22: error: unknown type name 'URLContext'
ffmpeg.c:161:23: error: unknown type name 'URLContext'
ffmpeg.c:167:26: error: unknown type name 'URLContext'
ffmpeg.c:173:23: error: unknown type name 'URLContext'
ffmpeg.c:179:1: error: unknown type name 'URLProtocol'
ffmpeg.c:180:5: warning: initialization makes integer from pointer without a cast [enabled by default]
ffmpeg.c:180:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:181:5: error: 'file_open' undeclared here (not in a function)
ffmpeg.c:181:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:181:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:182:5: error: 'file_read' undeclared here (not in a function)
ffmpeg.c:182:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:182:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:183:5: error: 'file_write' undeclared here (not in a function)
ffmpeg.c:183:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:183:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:184:5: error: 'file_seek' undeclared here (not in a function)
ffmpeg.c:184:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:184:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:185:5: error: 'file_close' undeclared here (not in a function)
ffmpeg.c:185:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:185:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:187:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:187:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:188:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:188:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c:189:5: warning: excess elements in scalar initializer [enabled by default]
ffmpeg.c:189:5: warning: (near initialization for 'file_protocol') [enabled by default]
ffmpeg.c: In function 'mpeg1_write_trailer':
ffmpeg.c:202:5: warning: implicit declaration of function 'put_buffer' [-Wimplicit-function-declaration]
ffmpeg.c:203:5: warning: implicit declaration of function 'put_flush_packet' [-Wimplicit-function-declaration]
ffmpeg.c: In function 'ffmpeg_init':
ffmpeg.c:225:24: error: request for member 'url_read' in something not a structure or union
ffmpeg.c:225:50: error: request for member 'url_read' in something not a structure or union
ffmpeg.c:226:24: error: request for member 'url_write' in something not a structure or union
ffmpeg.c:226:50: error: request for member 'url_write' in something not a structure or union
ffmpeg.c:227:24: error: request for member 'url_seek' in something not a structure or union
ffmpeg.c:227:50: error: request for member 'url_seek' in something not a structure or union
ffmpeg.c:228:24: error: request for member 'url_close' in something not a structure or union
ffmpeg.c:228:50: error: request for member 'url_close' in something not a structure or union
ffmpeg.c:236:5: warning: #warning av_register_protocolXXX missing [-Wcpp]
ffmpeg.c: In function 'ffmpeg_open':
ffmpeg.c:367:9: warning: 'av_new_stream' is deprecated (declared at /usr/include/libavformat/avformat.h:1557) [-Wdeprecated-declarations]
ffmpeg.c:422:5: warning: implicit declaration of function 'av_set_parameters' [-Wimplicit-function-declaration]
ffmpeg.c:448:5: warning: 'avcodec_open' is deprecated (declared at /usr/include/libavcodec/avcodec.h:3380) [-Wdeprecated-declarations]
ffmpeg.c:503:9: warning: implicit declaration of function 'url_fopen' [-Wimplicit-function-declaration]
ffmpeg.c:503:52: error: 'URL_WRONLY' undeclared (first use in this function)
ffmpeg.c:503:52: note: each undeclared identifier is reported only once for each function it appears in
ffmpeg.c:534:5: warning: implicit declaration of function 'av_write_header' [-Wimplicit-function-declaration]
ffmpeg.c: In function 'ffmpeg_close':
ffmpeg.c:601:9: warning: implicit declaration of function 'url_fclose' [-Wimplicit-function-declaration]
ffmpeg.c: In function 'ffmpeg_put_frame':
ffmpeg.c:661:9: warning: 'avcodec_encode_video' is deprecated (declared at /usr/include/libavcodec/avcodec.h:4077) [-Wdeprecated-declarations]
make: *** [ffmpeg.o] Error 1
```

**Comment by Fak3** [comment]
I managed to make it work with ffmpeg 0.11 in my fork https://github.com/Fak3/motion
Though i dropped mpeg-1 support.
